### ISSUE TITLE
Plugin not available in Schematic Editor (eeschema), only in PCB Editor

### ISSUE THREAD

**Issue by craigarno** [Sajitha-Aldeniya/KiCAD-Schematic-Blocks-Plugin#7]
**Windows 11 and Windows 10
KiCad 7.0.9
Schematic Blocks 0.1**

This solution being a schematic blocks plugin, and not a PCB blocks plugin, I was surprised that it only shows and has to be launched from the PCB editor.

Can this plugin show in the schematic editor (so I don't have to launch the PCB editor for "schematic block" access)?  And as long as it can't take clips of PCB layouts, be removed from the PCB editor?

This plugin otherwise works on my setup saving to a network drive, and to the local drive under KiCad 6 and KiCad 7.  And KiCad 6 blocks do import to KiCad7.  The reverse direction, not so much, just like KiCad.

I'll have to determine best refactoring for reuse of my schematics.

Thanks,
Craig

**Comment by Sajitha-Aldeniya** [comment]
Craig, Thanks for reaching out. Currently, KiCAD isn't have a API system for the Schematic Editor. That's why you have to launch all your plug-ins from the PCB editor.  So, until the KiCAD developers add API support for the Schematic Editor, the plug-in stuck in the PCB Editor. 

Thank you,
Sajitha Aldeniya.

**Comment by craigarno** [comment]
I guess I didn't expect that, but it is understandable, and Schematic Blocks does work.  Thank you for explaining.
